### ISSUE TITLE
tests fail because audiotechnica.com went away 

### ISSUE THREAD

**Issue by samth** [greghendershott/http#15]
See http://drdr.racket-lang.org/66738/cs/racket/share/pkgs/http/http/request.rkt

**Comment by samth** [comment]
It is defined for pkg-build but not for drdr (which has a full network connection and where the tests ought to work).

**Comment by greghendershott** [comment]
Ah!

In the future, I _might_ need some similar env var on drdr, because the web in 2024 is full of anti-scraping software, so conceivably an HTTP request might work OK from github.com but not from drdr.racket-lang.org (or even vice versa). But can cross that bridge whenever.

Meanwhile I'll just remove that example site (and, if I can find one quickly, add another multiple redirect site example).
